//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RLRes.rc
//

#define IDB_BEAR_ATTACK_HTH							101
#define IDB_BEAR_DEAD								102
#define IDB_BEAR_HITTED								103
#define IDB_BEAR_MOVE								104
#define IDB_BEAR_SLEEP								105
#define IDB_BEAR_STOP								106
#define IDB_DOG_ATTACK_HTH							107
#define IDB_DOG_DEAD								108
#define IDB_DOG_HITTED								109
#define IDB_DOG_MOVE								110
#define IDB_DOG_SLEEP								111
#define IDB_DOG_STOP								112
#define IDB_FLATSNAKE_ATTACK_HTH					113
#define IDB_FLATSNAKE_DEAD							114
#define IDB_FLATSNAKE_HITTED						115
#define IDB_FLATSNAKE_MOVE							116
#define IDB_FLATSNAKE_SLEEP							117
#define IDB_FLATSNAKE_STOP							118
#define IDB_HU_ARMOR_ATTACK_AXE						119
#define IDB_HU_ARMOR_ATTACK_DAGGER					120
#define IDB_HU_ARMOR_ATTACK_HTH						121
#define IDB_HU_ARMOR_ATTACK_MACE					122
#define IDB_HU_ARMOR_ATTACK_SWORD					123
#define IDB_HU_ARMOR_CONCENTRATE					124
#define IDB_HU_ARMOR_DEAD							125
#define IDB_HU_ARMOR_HITTED							126
#define IDB_HU_ARMOR_MOVE							127
#define IDB_HU_ARMOR_SLEEP							128
#define IDB_HU_ARMOR_STOP							129
#define IDB_HU_CLOTH_ATTACK_AXE						130
#define IDB_HU_CLOTH_ATTACK_DAGGER					131
#define IDB_HU_CLOTH_ATTACK_HTH						132
#define IDB_HU_CLOTH_ATTACK_MACE					133
#define IDB_HU_CLOTH_ATTACK_SWORD					134
#define IDB_HU_CLOTH_CONCENTRATE					135
#define IDB_HU_CLOTH_DEAD							136
#define IDB_HU_CLOTH_HITTED							137
#define IDB_HU_CLOTH_MOVE							138
#define IDB_HU_CLOTH_SLEEP							139
#define IDB_HU_CLOTH_STOP							140
#define IDB_HU_DRESS1_ATTACK_AXE					141
#define IDB_HU_DRESS1_ATTACK_DAGGER					142
#define IDB_HU_DRESS1_ATTACK_HTH					143
#define IDB_HU_DRESS1_ATTACK_MACE					144
#define IDB_HU_DRESS1_ATTACK_SWORD					145
#define IDB_HU_DRESS1_CONCENTRATE					146
#define IDB_HU_DRESS1_DEAD							147
#define IDB_HU_DRESS1_HITTED						148
#define IDB_HU_DRESS1_MOVE							149
#define IDB_HU_DRESS1_SLEEP							150
#define IDB_HU_DRESS1_STOP							151
#define IDB_HU_DRESS2_ATTACK_AXE					152
#define IDB_HU_DRESS2_ATTACK_DAGGER					153
#define IDB_HU_DRESS2_ATTACK_HTH					154
#define IDB_HU_DRESS2_ATTACK_MACE					155
#define IDB_HU_DRESS2_ATTACK_SWORD					156
#define IDB_HU_DRESS2_CONCENTRATE					157
#define IDB_HU_DRESS2_DEAD							158
#define IDB_HU_DRESS2_HITTED						159
#define IDB_HU_DRESS2_MOVE							160
#define IDB_HU_DRESS2_SLEEP							161
#define IDB_HU_DRESS2_STOP							162
#define IDB_HU_DRESS3_ATTACK_AXE					163
#define IDB_HU_DRESS3_ATTACK_DAGGER					164
#define IDB_HU_DRESS3_ATTACK_HTH					165
#define IDB_HU_DRESS3_ATTACK_MACE					166
#define IDB_HU_DRESS3_ATTACK_SWORD					167
#define IDB_HU_DRESS3_CONCENTRATE					168
#define IDB_HU_DRESS3_DEAD							169
#define IDB_HU_DRESS3_HITTED						170
#define IDB_HU_DRESS3_MOVE							171
#define IDB_HU_DRESS3_SLEEP							172
#define IDB_HU_DRESS3_STOP							173
#define IDB_HU_LEATH_ATTACK_AXE						174
#define IDB_HU_LEATH_ATTACK_DAGGER					175
#define IDB_HU_LEATH_ATTACK_HTH						176
#define IDB_HU_LEATH_ATTACK_MACE					177
#define IDB_HU_LEATH_ATTACK_SWORD					178
#define IDB_HU_LEATH_CONCENTRATE					179
#define IDB_HU_LEATH_DEAD							180
#define IDB_HU_LEATH_HITTED							181
#define IDB_HU_LEATH_MOVE							182
#define IDB_HU_LEATH_SLEEP							183
#define IDB_HU_LEATH_STOP							184
#define IDB_HU_MESH_ATTACK_AXE						185
#define IDB_HU_MESH_ATTACK_DAGGER					196
#define IDB_HU_MESH_ATTACK_HTH						187
#define IDB_HU_MESH_ATTACK_MACE						188
#define IDB_HU_MESH_ATTACK_SWORD					189
#define IDB_HU_MESH_CONCENTRATE						190
#define IDB_HU_MESH_DEAD							191
#define IDB_HU_MESH_HITTED							192
#define IDB_HU_MESH_MOVE							193
#define IDB_HU_MESH_SLEEP							194
#define IDB_HU_MESH_STOP							195
#define IDB_HU_NUDE_ATTACK_AXE						296
#define IDB_HU_NUDE_ATTACK_DAGGER					297
#define IDB_HU_NUDE_ATTACK_HTH						298
#define IDB_HU_NUDE_ATTACK_MACE						299
#define IDB_HU_NUDE_ATTACK_SWORD					200
#define IDB_HU_NUDE_CONCENTRATE						201
#define IDB_HU_NUDE_DEAD							202
#define IDB_HU_NUDE_HITTED							203
#define IDB_HU_NUDE_MOVE							204
#define IDB_HU_NUDE_SLEEP							205
#define IDB_HU_NUDE_STOP							206
#define IDB_HU_PADS_ATTACK_AXE						207
#define IDB_HU_PADS_ATTACK_DAGGER					208
#define IDB_HU_PADS_ATTACK_HTH						209
#define IDB_HU_PADS_ATTACK_MACE						210
#define IDB_HU_PADS_ATTACK_SWORD					211
#define IDB_HU_PADS_CONCENTRATE						212
#define IDB_HU_PADS_DEAD							213
#define IDB_HU_PADS_HITTED							214
#define IDB_HU_PADS_MOVE							215
#define IDB_HU_PADS_SLEEP							216
#define IDB_HU_PADS_STOP							217
#define IDB_MARSHPLANT_ATTACK_HTH					218
#define IDB_MARSHPLANT_CONCENTRATE					219
#define IDB_MARSHPLANT_DEAD							220
#define IDB_MARSHPLANT_HITTED						221
#define IDB_MARSHPLANT_STOP							222
#define IDB_PINKSNAKE_ATTACK_HTH					223
#define IDB_PINKSNAKE_DEAD							224
#define IDB_PINKSNAKE_HITTED						225
#define IDB_PINKSNAKE_MOVE							226
#define IDB_PINKSNAKE_SLEEP							227
#define IDB_PINKSNAKE_STOP							228
#define IDB_SPIDER_ATTACK_HTH						229
#define IDB_SPIDER_DEAD								230
#define IDB_SPIDER_MOVE								231
#define IDB_SPIDER_STOP								232
#define IDB_TITLE									233
#define IDB_ACTION_BUTTONS							234
#define IDB_COMBAT_ACTION							235
#define IDB_CURSOR									236
#define IDB_ELEVATOR								237
#define IDB_ELEVATOR_BKG							238
#define IDB_ENERGYBAR								239
#define IDB_FLAG_BUTTONS							240
#define IDB_LANDMAP									241
#define IDB_MENU_BKG								242
#define IDB_PANEL_BKG								243
#define IDB_PANEL_BORDER							244
#define IDB_PANEL_CLOSE								245
#define IDB_POCKET_ARMORS							246
#define IDB_POCKET_INGREDIENTS						247
#define IDB_POCKET_OTHERS							248
#define IDB_POCKET_WEAPONS							249
#define IDB_PROGRESS_BUTTONS						250
#define IDB_SELECT_BUTTONS							251
#define IDB_SETTING_BUTTONS							252
#define IDB_SHORTCUT_LOGOS							253
#define IDB_SPELLLIST								254
#define IDB_WK_MACE									255
#define IDB_ARMORS									256
#define IDB_DAGGERS									257
#define IDB_DRINKS									258
#define IDB_FLOWERS									259
#define IDB_FRUITS									260
#define IDB_JEWELS									261
#define IDB_MD_AXE									262
#define IDB_MD_MACE									263
#define IDB_MESSAGE									264
#define IDB_MONEY									265
#define IDB_POTIONS									266
#define IDB_ST_AXE									267
#define IDB_ST_MACE									268
#define IDB_SWORDS									269
#define IDB_MAP_BRIDGES								270
#define IDB_MAP_DECORATION							271
#define IDB_MAP_GROUND								272
#define IDB_MAP_ITEMS								273
#define IDB_MAP_PATHNODES							274

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        369
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
